### ISSUE TITLE
Problem installing the addon

### ISSUE THREAD

**Issue by Moheeb77** [thomasklosinsky/purchase_barcode_qweb#1]
Hi
I tried to install the purchase_barcode_qweb but I got the following error. Your help would be highly appreciated.

Regards

Odoo Server Error
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 8.0-20150701\server\.\openerp\http.py", line 537, in _handle_exception
  File "C:\Program Files (x86)\Odoo 8.0-20150701\server\.\openerp\http.py", line 574, in dispatch
  File "C:\Program Files (x86)\Odoo 8.0-20150701\server\.\openerp\http.py", line 310, in _call_function
  File "C:\Program Files (x86)\Odoo 8.0-20150701\server\.\openerp\service\model.py", line 113, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150701\server\.\openerp\http.py", line 307, in checked_call
  File "C:\Program Files (x86)\Odoo 8.0-20150701\server\.\openerp\http.py", line 803, in __call__
  File "C:\Program Files (x86)\Odoo 8.0-20150701\server\.\openerp\http.py", line 403, in response_wrap
  File "C:\Program Files (x86)\Odoo 8.0-20150701\server\openerp\addons\web\controllers\main.py", line 948, in call_button
  File "C:\Program Files (x86)\Odoo 8.0-20150701\server\openerp\addons\web\controllers\main.py", line 936, in _call_kw
  File "C:\Program Files (x86)\Odoo 8.0-20150701\server\.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150701\server\openerp\addons\base\module\module.py", line 450, in button_immediate_install
  File "C:\Program Files (x86)\Odoo 8.0-20150701\server\.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150701\server\openerp\addons\base\module\module.py", line 498, in _button_immediate_function
  File "C:\Program Files (x86)\Odoo 8.0-20150701\server\.\openerp\modules\registry.py", line 370, in new
  File "C:\Program Files (x86)\Odoo 8.0-20150701\server\.\openerp\modules\loading.py", line 355, in load_modules
  File "C:\Program Files (x86)\Odoo 8.0-20150701\server\.\openerp\modules\loading.py", line 255, in load_marked_modules
  File "C:\Program Files (x86)\Odoo 8.0-20150701\server\.\openerp\modules\loading.py", line 176, in load_module_graph
  File "C:\Program Files (x86)\Odoo 8.0-20150701\server\.\openerp\modules\loading.py", line 118, in _load_data
  File "C:\Program Files (x86)\Odoo 8.0-20150701\server\.\openerp\tools\convert.py", line 901, in convert_file
  File "C:\Program Files (x86)\Odoo 8.0-20150701\server\.\openerp\tools\convert.py", line 987, in convert_xml_import
  File "C:\Program Files (x86)\Odoo 8.0-20150701\server\.\openerp\tools\convert.py", line 853, in parse
  File "C:\Program Files (x86)\Odoo 8.0-20150701\server\.\openerp\tools\convert.py", line 755, in _tag_record
  File "C:\Program Files (x86)\Odoo 8.0-20150701\server\.\openerp\tools\convert.py", line 832, in id_get
  File "C:\Program Files (x86)\Odoo 8.0-20150701\server\.\openerp\tools\convert.py", line 843, in model_id_get
  File "C:\Program Files (x86)\Odoo 8.0-20150701\server\.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150701\server\openerp\addons\base\ir\ir_model.py", line 936, in xmlid_to_res_model_res_id
  File "C:\Program Files (x86)\Odoo 8.0-20150701\server\.\openerp\api.py", line 241, in wrapper
  File "<string>", line 2, in xmlid_lookup
  File "C:\Program Files (x86)\Odoo 8.0-20150701\server\.\openerp\tools\cache.py", line 74, in lookup
  File "C:\Program Files (x86)\Odoo 8.0-20150701\server\openerp\addons\base\ir\ir_model.py", line 926, in xmlid_lookup
ParseError: "External ID not found in the system: purchase_barcode_qweb.paperformat_barcode_label_purchase" while parsing file:///C:/Users/XXXX/AppData/Local/OpenERP%20S.A/Odoo/addons/8.0/puchase_barcode_qweb/purchase_barcode_qweb_report.xml:16, near
<record id="purchase_barcode_qweb" model="ir.actions.report.xml">
            <field name="paperformat_id" ref="purchase_barcode_qweb.paperformat_barcode_label_purchase"/>
        </record>

**Comment by pvd276** [comment]
me too
get this error when install module

**Comment by thanhchatvn** [comment]
i fixed this error but i can not push commit to this git source

**Comment by thanhchatvn** [comment]
Hi all,

- Fixed from repo:  $ git clone https://github.com/thanhchatvn/purchase_barcode_qweb.git

Good luck.

**Comment by thomasklosinsky** [comment]
@thanhchatvn 
Thank you for the fix. I have the product_barcode_qweb module also installed, so maybe that one suppressed the install error...
Could you do the changes in my files also and make a pull request?

**Comment by thanhchatvn** [comment]
@thomas: You can clone this repo and depends old module, will be fixed , good luck

**Comment by thomasklosinsky** [comment]
@thanhchatvn: I watched your changes, but you changed everything back to "normal" and I also made a diff check and no diffs where found in our two modules. Do you know which changes you made?

**Comment by thomasklosinsky** [comment]
should be gone now...
