### ISSUE TITLE
Permissions error

### ISSUE THREAD

**Issue by aitorbouzas** [thomasklosinsky/purchase_barcode_qweb#3]
I'm having this permission error:

`Traceback (most recent call last):
  File "/opt/odoo/addons/report/controllers/main.py", line 125, in report_download
    response = self.report_routes(reportname, converter='pdf', **dict(data))
  File "/opt/odoo/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/report/controllers/main.py", line 65, in report_routes
    pdf = report_obj.get_pdf(cr, uid, docids, reportname, data=options_data, context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons/report/models/report.py", line 191, in get_pdf
    html = self.get_html(cr, uid, ids, report_name, data=data, context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons/report/models/report.py", line 166, in get_html
    return particularreport_obj.render_html(cr, uid, ids, data=data, context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons/report/models/abstract_report.py", line 66, in render_html
    return self.pool['report'].render(cr, uid, [], self._template, docargs, context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons/website_report/report.py", line 47, in render
    return super(Report, self).render(cr, uid, ids, template, values=values, context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons/report/models/report.py", line 152, in render
    return view_obj.render(cr, uid, template, values, context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons/website/models/ir_ui_view.py", line 172, in render
    return super(view, self).render(cr, uid, id_or_xml_id, values=values, engine=engine, context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_ui_view.py", line 1017, in render
    return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 262, in render
    return self.render_node(self.get_template(id_or_xml_id, qwebcontext), qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 301, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 322, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 301, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 322, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 301, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 322, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 301, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 322, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 299, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 423, in render_tag_foreach
    ru.append(self.render_element(element, template_attributes, generated_attributes, copy_qwebcontext))
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 322, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 299, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 423, in render_tag_foreach
    ru.append(self.render_element(element, template_attributes, generated_attributes, copy_qwebcontext))
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 322, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 301, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 322, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 283, in render_node
    self, element, attribute_name, attribute_value, qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 358, in render_att_att
    return [(attribute_name[6:], self.eval(attribute_value, qwebcontext))]
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 206, in eval
    raise_qweb_exception(message="Could not evaluate expression %r" % expr, expression=expr, template=template)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 203, in eval
    return qwebcontext.safe_eval(expr)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 89, in safe_eval
    return eval(expr, None, locals_dict, nocopy=True, locals_builtins=True)
  File "/opt/odoo/openerp/tools/safe_eval.py", line 314, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/opt/odoo/addons/purchase_barcode_qweb/report/purchase_barcode_print.py", line 73, in _generateBarcode
    Code128().getImage(barcode_string, path="./").save(fp, "PNG")
  File "/opt/odoo/addons/purchase_barcode_qweb/report/Code128.py", line 233, in getImage
    decodeFontFile(courB08_pil ,path+"courB08.pil")
  File "/opt/odoo/addons/purchase_barcode_qweb/report/Code128.py", line 274, in decodeFontFile
    open (file, "wb").write(decompress(decodestring(data)))
QWebException: "13
Permission denied" while evaluating
"'data:image/png;base64,'+generateBarcode(label_data['default_code'])"`

Where is the module trying to write the report files? Did changes in the module files permission, but it didn't work.

Thanks

**Comment by thomasklosinsky** [comment]
sorry for that. I will just upload an update and hope this error will be gone in your installation.

**Comment by thomasklosinsky** [comment]
please have a new try now...

**Comment by Softdil** [comment]
I just updated it, with the new "product_brand" dependency, but it's still giving me this error.

**Comment by thomasklosinsky** [comment]
Very sorry to hear that. I believe that I can't help in this issue since it seems to be something local. I just installed this module on a new instance and it's working fine.

You may want to check out this thread:
https://www.odoo.com/de_DE/forum/hilfe-1/question/what-is-this-error-qwebexception-13-permission-denied-91522

**Comment by Nacimus** [comment]
hello, thanks for this useful module, although I'm facing the same permission problem

**Comment by thomasklosinsky** [comment]
So changing the permissions of the modules folder didn't work?
